(function (global) {
  'use strict';

  const { $ } = global.SirepUtils;

  const elements = {
    btnIniciar: $('#btnIniciar'),
    btnPausar: $('#btnPausar'),
    btnContinuar: $('#btnContinuar'),
    barTotal: $('#barTotal'),
    lblTotal: $('#lblTotal'),
    ultima: $('#ultimaAtualizacao'),
    tbody: $('#tbody'),
    btnProximo: $('#btnProximo'),
    btnAnterior: $('#btnAnterior'),
    lblPaginaTotal: $('#lblPaginaTotal'),
    footerInfo: $('#footerInfo'),
    wrapPlanos: $('#wrapPlanos'),
    tbodyOcc: $('#tbodyOcc'),
    btnProximoOcc: $('#btnProximoOcc'),
    btnAnteriorOcc: $('#btnAnteriorOcc'),
    lblPaginaTotalOcc: $('#lblPaginaTotalOcc'),
    footerInfoOcc: $('#footerInfoOcc'),
    filtroOcorrToggle: $('#filtroOcorrToggle'),
    filtroOcorrMenu: $('#filtroOcorrMenu'),
    filtroOcorrTrigger: $('#filtroOcorrTrigger'),
    wrapOcorr: $('#wrapOcorr'),
    estadoTexto: $('#estadoTexto'),
    subtabPlanos: $('#subtabPlanos'),
    subtabOcorr: $('#subtabOcorr'),
    badgeOcorr: $('#badgeOcorr'),
    modalConcluido: $('#modalConcluido'),
    btnModalOk: $('#btnModalOk'),
    btnModalClose: $('#btnModalClose'),
    logsHeader: $('#logsHeader'),
    logsBody: $('#logsBody'),
    tbodyLogs: $('#tbodyLogs'),
    logsFrom: $('#logsFrom'),
    logsTo: $('#logsTo'),
    btnExportLogs: $('#btnExportLogs'),
    treatmentLogsHeader: $('#treatmentLogsHeader'),
    treatmentLogsBody: $('#treatmentLogsBody'),
    treatmentLogsWrap: $('#treatmentLogsWrap'),
    treatmentLogsFrom: $('#treatmentLogsFrom'),
    treatmentLogsTo: $('#treatmentLogsTo'),
    btnTreatmentExportLogs: $('#btnTreatmentExportLogs'),
    tratamentoEstado: $('#tratamentoEstado'),
    btnTratamentoSeed: $('#btnTratamentoSeed'),
    btnTratamentoIniciar: $('#btnTratamentoIniciar'),
    btnTratamentoPausar: $('#btnTratamentoPausar'),
    btnTratamentoContinuar: $('#btnTratamentoContinuar'),
    treatmentQueueTabFila: $('#treatmentQueueTabFila'),
    treatmentQueueTabRescindidos: $('#treatmentQueueTabRescindidos'),
    treatmentQueuePanel: $('#treatmentQueuePanel'),
    treatmentRescindidosPanel: $('#treatmentRescindidosPanel'),
    tbodyTratamentoFila: $('#tbodyTratamentoFila'),
    tratamentoEmpty: $('#tratamentoEmpty'),
    treatmentSearch: $('#treatmentSearch'),
    tbodyTratamentoTabela: $('#tbodyTratamentoTabela'),
    treatmentTableInfo: $('#treatmentTableInfo'),
    treatmentTablePageLabel: $('#treatmentTablePageLabel'),
    btnTreatmentTablePrev: $('#btnTreatmentTablePrev'),
    btnTreatmentTableNext: $('#btnTreatmentTableNext'),
    tbodyTratamentoLogs: $('#tbodyTratamentoLogs'),
    treatmentQueueCount: $('#treatmentQueueCount'),
    treatmentRescindidosCount: $('#treatmentRescindidosCount'),
    treatmentRescindidosRemaining: $('#treatmentRescindidosRemaining'),
    treatmentRescindidosRemainingValue: $('#treatmentRescindidosRemainingValue'),
    inputRescindidosFrom: $('#inputRescindidosFrom'),
    inputRescindidosTo: $('#inputRescindidosTo'),
    btnDownloadRescindidos: $('#btnDownloadRescindidos'),
    tabGestao: $('#tab-gestao'),
    tabTratamento: $('#tab-tratamento'),
  };

  global.SirepDOM = {
    elements,
    tabs: Array.from(document.querySelectorAll('.tab')),
    sections: Array.from(document.querySelectorAll('.content > section')),
  };
})(window);
