from enum import StrEnum, auto

class PlanStatus(StrEnum):
    NOVO = "NOVO"
    SEM_TRATAMENTO = "SEM_TRATAMENTO"
    PASSIVEL_RESC = "P_RESC"
    LIQUIDADO = "LIQUIDADO"
    RESCINDIDO = "RESCINDIDO"
    NAO_RESCINDIDO = "NAO_RESCINDIDO"
    ESPECIAL = "ESPECIAL"

class Step(StrEnum):
    ETAPA_1 = "ETAPA_1_CAPTURA_PLANOS"
    ETAPA_2 = "ETAPA_2_SITUACAO_ESPECIAL"
    ETAPA_3 = "ETAPA_3_LIQUIDACAO_ANTERIOR"
    ETAPA_4 = "ETAPA_4_GUIA_GRDE"
    ETAPA_5 = "ETAPA_5_APROVEIT_RECOLH"  # (Tratamento 1)
    ETAPA_7 = "ETAPA_7_E206_SUBST_CONFxNOT"
    ETAPA_8 = "ETAPA_8_PESQ_GUIAS_PIG"
    ETAPA_9 = "ETAPA_9_LANC_GUIAS_PIG"
    ETAPA_10 = "ETAPA_10_SITUACAO_PLANO"
    ETAPA_11 = "ETAPA_11_RESCISAO"
    ETAPA_12 = "ETAPA_12_COMUNICACAO"
    ETAPA_13 = "ETAPA_13_DOSSIE"